syntax on
set number
set showbreak=+++
set linebreak
set showmatch
set hlsearch
set autoindent
set tabstop=4
set shiftwidth=4
set smartindent
set smarttab
set softtabstop=4
set ruler
set undolevel=10000
set backspace=indent,eol,start
set expandtab
